controller_manager:
  ros__parameters:
    update_rate: 225  # Hz
    
# This controller is used to publish the joint states (position, velocity, effort) to the /joint_states topic.
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      

    position_controller:
      type: position_controllers/JointGroupPositionController



position_controller:
  ros__parameters:
    joints:
      
      - j0
      - j1
      - j2
      - j3
      
